apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: delta
  labels:
    type: local
spec:
  storageClassName: database
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql/delta"